### ISSUE TITLE
Please add a ChangeLog

### ISSUE THREAD

**Issue by postmodern** [seuros/hosted_graphite#11]
It's nice to have a high-level summary of the changes made between releases.

**Comment by jeremywadsack** [comment]
As of e72dac42d17867d8cbe48fbef491d2262eaf759d, there is a change log file, but the version listed (1.0.1) doesn't match `HostedGraphite::VERSION` (0.1.1). It would help to have these in sync. (And some more details about the releases like the breaking change to require setting `protocol` before each call.)
