### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by cambridgemike** [seuros/hosted_graphite#5]
I noticed I'm taking a real performance hit using hosted graphite (I think it's statsd, not HG, since HG is just wrapping it).

https://gist.github.com/cambridgemike/f925779887fd5417a61c

I read the bit on statsd about using a local dns cache, which I believe OS X has on by default.

Any thoughts?

**Comment by hale** [comment]
Would it be possible to use a static IP for the HostedGraphite endpoint instead of a hostname? https://github.com/seuros/hosted_graphite/blob/master/lib/hosted_graphite/protocols/statsd.rb#L9
