### ISSUE TITLE
Cannot pass optional UNIX timestamp with a metric

### ISSUE THREAD

**Issue by maxkohl88** [seuros/hosted_graphite#6]
Hey folks!

I'm trying to pass a UNIX timestamp in with a metric as a third argument, as mentioned here:

http://docs.hostedgraphite.com/#metric-data-format

but I got an error saying wrong number of arguments (3 for 2). Took a quick peek into the source and it looks like the send_metric method for Protocol does not accept the optional timestamp: 

https://github.com/seuros/hosted_graphite/blob/master/lib/hosted_graphite/protocol.rb

I'm running some queued monitoring and need to pass that timestamp through to ensure accurate data/graphing. 

Is that something that could be patched up? Thanks!

**Comment by seuros** [comment]
Can you send a PR ? I will merge and release a new version.

**Comment by maxkohl88** [comment]
No problemo, I just submitted a pull request for this:

https://github.com/seuros/hosted_graphite/pull/7

**Comment by seuros** [comment]
Thank you.

**Comment by maxkohl88** [comment]
For sure, and thanks for responding quickly!
