### ISSUE TITLE
Allow to deactivate the gem functionality

### ISSUE THREAD

**Issue by gottfrois** [seuros/hosted_graphite#8]
Hey guys, thanks for the great work here!

Would be nice to be able to enable/disable the gem since we might not want to push data from test, staging or development envs.

For example in rails it would be done in an initializer just like when setting the protocol. You'll probably want to not raise an exception if the key is missing as well since in dev env you might simply not have it at all.

Thanks !

**Comment by uiltondutra** [comment]
Currently I'm using the code below to deactivate the gem in test and development.
```
if ["test", "development"].include?(env)
  require 'securerandom'
  require 'hosted_graphite/testing'
  HostedGraphite.api_key = SecureRandom.uuid
end
```

**Comment by antstorm** [comment]
#16
